- name: generate iptables.sh
  template: dest=/usr/local/bin/iptables.sh src=../templates/iptablesSkelton.js2 mode=0755
  sudo: yes
  tags:
    - iptables

- name: iptables適用  
  command: /usr/local/bin/iptables.sh
  sudo: yes
  tags:
    - iptables

- name: 再起動時にも適用する
  lineinfile: line=/usr/local/bin/iptables insertafter=EOF dest=/etc/rc.local
  sudo: yes
  tags:
    - iptables

